apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
  - image: busybox
    name: busybox-container
#    args: [""echo", "doing some debugging"]
#  OR
#    command: ["printenv"]
#    args: ["HOSTNAME", "KUBERNETES_PORT"]
# OR
    command: ["sh"]
    args: ["-c", "sleep 1000"]
