apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  initContainers:
  - name: add-host
    image: busybox
    command: ['sh', '-c', 'cat /etc/hosts >/tmp/hosts.new && echo "10.102.13.177 mysql-service" >> /tmp/hosts.new && echo "10.98.67.208 nginx-internal-service" >> /tmp/hosts.new && cat /tmp/hosts.new >/etc/hosts']
    volumeMounts:
    - name: hosts-volume
      mountPath: /etc/hosts
  containers:
  - name: my-container
    image: my-image
    # Rest of your container configuration
  volumes:
  - name: hosts-volume
    configMap:
      name: hosts-config
