apiVersion: v1
kind: Service
metadata:
  name: nginx-internal-service
  labels:
    app: nginx
    svc: nginx-internal-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080   # Port on your pods
#  type: LoadBalancer


