apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
#  labels:
#    type: local
spec:
  hostPath:
# At below line, Specify the path on the host machine(on db-pod)  where the volume will be mounted
#    path: "/home/admin1/mysql-pv-moutpoint" 
    path: /mnt/data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteMany




