kind: Service
apiVersion: v1
metadata:
  name: wordpress-service
  labels:
    app: wordpress
    svc: label-wordpress
spec:
 type: LoadBalancer
 selector:
   app: wordpress
 ports:
   - name: http
     protocol: TCP
     port: 8080
     targetPort: 80

